### ISSUE TITLE
Can't remove the media notification when app is killed

### ISSUE THREAD

**Issue by marianoarga** [aliyazdi75/flutter_media_notification#1]
Launch media notification, kill the app, the media notification remains opened and touching it does not open the app or make anything.

Thank you.

**Comment by aliyazdi75** [comment]
@marianoarga hey, yes it doesn't kill, please wait for next week, I'm gonna improve it and add this feature.

**Comment by marianoarga** [comment]
Thank you :)

**Comment by aliyazdi75** [comment]
@marianoarga 
`flutter_media_notification` has been updated to `^1.2.5`.
Please update and enjoy it.

**Comment by marianoarga** [comment]
@aliyazdi75 thank you sir
