### ISSUE TITLE
@aliyazdi75 Regarding Music Playing Even After The App is Closed

### ISSUE THREAD

**Issue by OjasKarmarkar** [aliyazdi75/flutter_media_notification#3]
Used your MediaNotification package.. everything works like a charm! But due to that even after the app is killed the music is still running.. Do i have to use Hidenotification() compulsorily?

**Comment by aliyazdi75** [comment]
No it doesn't need.
When `MediaNotification.show` is invoked, it makes a android service and in app killing, `MediaNotification` kills service and it takes 5 or less seconds for stopping your music and this is happened normally.
If your music still running after 5 seconds please tell me more about this situation.

**Comment by andrewpmoore** [comment]
I'm also seeing that it just keeps playing.
I keep getting a repeat of this in the logs

D/FlutterNativeView(21008): FlutterView.send called on a detached view, channel=xyz.luan/audioplayers

**Comment by OjasKarmarkar** [comment]
Yes I too get the same log repeatedly!!

**Comment by aliyazdi75** [comment]
I see.
It's not notification problem, it's `audioplayers` problem that should be fixed.
if you close app, notification will be closed. isn't it?

**Comment by OjasKarmarkar** [comment]
Yep Notification does get closed..But the problem occurs when this plugin
is used.. so m not sure whether it's related to this plugin or the audio
player plugin! Mind having a look at my music player source code?

**Comment by aliyazdi75** [comment]
No, you right. it happens.
But needs some changes on `audioplayers` plugin to make this work.
Maybe I will change on 'audioplayers' plugin github.
If you mind close this issue.

**Comment by OjasKarmarkar** [comment]
Done I'll close it right away.. Can u Also make the changes in
flute-music-player? A humble request!

**Comment by aliyazdi75** [comment]
Sure, as soon as possible.
